name: Build release

permissions:
  contents: write

# controls when the workflow will run
on:
  # triggers the workflow on push of tags that start with v (e.g. v1.2.9)
  push:
    tags: [ "v*" ]

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains a single job called "build"
  build:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $github_workspace, so your job can access it
      - uses: actions/checkout@v4

      # runs a set of commands using the runners shell
      - name: run a multi-line script
        run: |
          CURRENT_DIR=$(pwd)
          TEMP_DIR=$(mktemp -d)
          DEST_DIR="$TEMP_DIR/harambeschosen"
          
          mkdir -p "$DEST_DIR"
          cp -r localization "$DEST_DIR/"
          cp main.lua "$DEST_DIR/"
          
          mkdir -p "$DEST_DIR/assets"
          rsync -av --exclude='originals' assets/ "$DEST_DIR/assets/"
          
          (
            cd "$TEMP_DIR"
            zip -r "$CURRENT_DIR/harambeschosen.zip" harambeschosen
          )
          
          rm -rf "$TEMP_DIR"

      - name: list files
        run: ls -a
      - name: release
        uses: softprops/action-gh-release@v2
        if: startswith(github.ref, 'refs/tags/')
        with:
          files: harambeschosen.zip